blueprint:
  name: Annonce Alexa - Changement de Garde
  description: Annonce sur vos enceintes Alexa quand l'enfant arrive ou part.
  domain: automation
  input:
    custody_entity:
      name: Entité de Présence
      description: Le binary_sensor de présence de l'enfant.
      selector:
        entity:
          domain: binary_sensor
          integration: custody_schedule
    alexa_device:
      name: Appareil Alexa
      description: Le media_player Alexa qui fera l'annonce.
      selector:
        entity:
          domain: media_player
    arrival_message:
      name: Message d'arrivée
      description: Message à annoncer quand l'enfant arrive.
      default: "C'est la semaine de {{ state_attr(custody_entity, 'child_name') }}. Bienvenue à la maison !"
    departure_message:
      name: Message de départ
      description: Message à annoncer quand l'enfant part.
      default: "{{ state_attr(custody_entity, 'child_name') }} est maintenant chez l'autre parent. À bientôt !"

trigger:
  - platform: state
    entity_id: !input custody_entity
    from: "off"
    to: "on"
    id: "arrival"
  - platform: state
    entity_id: !input custody_entity
    from: "on"
    to: "off"
    id: "departure"

action:
  - service: notify.alexa_media
    data:
      target: !input alexa_device
      data:
        type: announce
        method: speak
      message: >
        {% if trigger.id == 'arrival' %}
          !input arrival_message
        {% else %}
          !input departure_message
        {% endif %}
